//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bloodbog_bdEntities : DbContext
    {
        public bloodbog_bdEntities()
            : base("name=bloodbog_bdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Campanas_Donacion> Campanas_Donacion { get; set; }
        public virtual DbSet<Tipo_Documento> Tipo_Documento { get; set; }
        public virtual DbSet<Agendamiento_Campana> Agendamiento_Campana { get; set; }
        public virtual DbSet<Banner> Banner { get; set; }
        public virtual DbSet<Clinicas_Bancos_Sangre> Clinicas_Bancos_Sangre { get; set; }
        public virtual DbSet<Estado_Solicitud> Estado_Solicitud { get; set; }
        public virtual DbSet<Lineas_Atencion> Lineas_Atencion { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Menu_Rol> Menu_Rol { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Solicitud_Recoleccion> Solicitud_Recoleccion { get; set; }
        public virtual DbSet<Tipo_Sangre> Tipo_Sangre { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
