//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud_Recoleccion
    {
        public int IdSolicitud { get; set; }
        public string Direccion_Donde { get; set; }
        public string LGN_Donde { get; set; }
        public string LTD_Donde { get; set; }
        public int IdEstado_Solicitud { get; set; }
        public int IdUsuario_Solicita { get; set; }
        public int IdUsuario_Recolecta { get; set; }
        public System.DateTime Fecha_Recoleccion { get; set; }
    
        public virtual Estado_Solicitud Estado_Solicitud { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
