//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Agendamiento_Campana = new HashSet<Agendamiento_Campana>();
            this.Banner = new HashSet<Banner>();
            this.Campanas_Donacion = new HashSet<Campanas_Donacion>();
            this.Clinicas_Bancos_Sangre = new HashSet<Clinicas_Bancos_Sangre>();
            this.Clinicas_Bancos_Sangre1 = new HashSet<Clinicas_Bancos_Sangre>();
            this.Solicitud_Recoleccion = new HashSet<Solicitud_Recoleccion>();
            this.Solicitud_Recoleccion1 = new HashSet<Solicitud_Recoleccion>();
        }
    
        public int IdUsuario { get; set; }
        public string Nombres { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string CorreoElectronico { get; set; }
        public int Peso { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string NumeroDocumento { get; set; }
        public string HashContrasena { get; set; }
        public int IdTipoDocumento { get; set; }
        public int IdTipoSangre { get; set; }
        public int IdRol { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agendamiento_Campana> Agendamiento_Campana { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Banner> Banner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Campanas_Donacion> Campanas_Donacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clinicas_Bancos_Sangre> Clinicas_Bancos_Sangre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clinicas_Bancos_Sangre> Clinicas_Bancos_Sangre1 { get; set; }
        public virtual Rol Rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Recoleccion> Solicitud_Recoleccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Recoleccion> Solicitud_Recoleccion1 { get; set; }
        public virtual Tipo_Documento Tipo_Documento { get; set; }
        public virtual Tipo_Sangre Tipo_Sangre { get; set; }
    }
}
